version: '3'

services:
    api_final_yatube:
        build: .
        container_name: api_final_yatube
        command: python yatube_api/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/opt/project
        ports:
            - "8000:8000"
